<!-- 
Xampp là chương trình tạo máy chủ Web được tích hợp sẵn Apache, PHP, MySQL, FTP Server, Mail Server và các công cụ như phpMyAdmin.
 Không như Appserv, Xampp có chương trình quản lý khá tiện lợi, cho phép chủ động bật tắt hoặc khởi động lại các dịch vụ máy chủ bất kỳ lúc nào. 

-ngôn ngữ php dùng làm chức năng đăng nhập, đki, chức năng tìm kiếm cho 1 trang web
*** CÀI ĐẶT XAMPP:
-tải xampp download,cữ mặc định "next" , sau đó finish là cài xong
-tạo 1 thư mục để chúa code php "HOANG_THUONG_PHP" trong thư mục "htdocs" của xampp

-->