<!-- TA ĐÃ HỌC CÂU LỆNH echo để in ra màn hình
- ta có thể dùng lệnh print để in chuỗi, số, gtri biến ra màn hình (tác dụng y hệt echo)
-tuy nhiên dự án thực tế ta rất ít dùng "print "
-->

<?php
echo "hello";
print "hello";
/*SỰ KHÁC BIỆT GIỮA echo VÀ print:
echo: ví dụ đếm chũ "hello" có bao nhiêu ký tự => nó đếm đc 5 và trả về 5
print: nó luôn trả về gtri =1 dù có bao nhiêu ký tự

=> ở 1 số bài cần biết chính xác chuỗi có ?ký tự thì print ko làm đc 
*/
?>