<!-- làm việc với file:
-đọc file
- xử lý file
- vòng lặp file
- tạo file
- viết vào file
- viết đè vào file
- upload file
-->
<?php
//1. ĐỌC FILE: ở đây là file.txt(file văn bản)
//ta tạo ra 1 file bài45.txt để đọc
//dùng hàm readfile("tenFIle");
echo readfile("BAI45.TXT");
/*hàm này sẽ đọc toàn bộ file bai45.txt và đếm số ký tự trong file:

 đây là bài 45 (có 45 ký tự)
 đọc nội dung file46 (có 46 ký tự)

 */
?>