<!-- ta sẽ chèn các thẻ h1->h6 , br(để xuống dòng),strong, b,u,i ... vào code php để tạo hiệu ứng HTML cho chữ -->

<?php
echo "xin chào <br> <h1> trần hải đăng </h1>";  //ta chèn thẻ h1 để biến "trần hải đăng" thành tiêu đề chính
//*** MẸO: cách chèn thẻ html vào ND php nhanh:
//ta bôi đen ND php , ALT+ W để nó bao lấy 2 đầu, sau đó đièn tên thẻ HTML
echo "<b>đăng </b>yeu <i>hương</i>";
?>