<!--
***HÔM NAY TA HỌC TẠO CSDL THỦ CÔNG (CHỨ CHƯA THAO TÁC BẰNG DÒNG LỆNH)
1. ta đặt tên database, chọn ngôn ngữ "utf8mb4_general_ci" -> bấm tạo
 2. ta bấm vào csdl vừa tạo , đặt tên bảng, chọn số cột ban đầu (sau này ta có thể thêm bớt or xóa đi các cột này)
 - đặt tên cho các cột, chọn KDL cho cột, kdl chính là các dạng ta đã học ở sql server
 -ĐỂ quay lại các csdl ta bấm vào chữ "máy chủ" góc trên bên trái -> chọn "cơ sở dữ liệu"
 ->chọn vào tên các bảng ta tạo (VD bảng "tài khoản") -> chọn chèn -> lúc này ta điền gtri các cột tương ứng vào ô gtri 
 -> sau khi điền gtri xong ta bấm thực hiện -> đã thêm dũ liệu vào bảng thành công 
-->