<!-- ta vào xampp, bật apache và mysql; sau khi bật mysql ta bấm admin
or ta vào đg dẫn localhost:8080/phpmyadmin/
-trên máy chủ ảo này đã có sẵn mysql để ta tạo csdl rồi
-ta đặt tên CSDL, chọn ngôn ngữ là "utf8mb4_general_ci" , sau đó bấm tạo => ta sẽ tạo đc 1 CSDL
*** lưu ý :ta chỉ có thể xóa các csdl do ta tạo, còn 5 csdl hệ thống ko dc xóa:
information_schema	
mysql		
performance_schema	
phpmyadmin		
test	
-muốn xóa csdl nào, tích vào ô vuông bên cạnh nó, sau đó chọn nút xóa ở duói nó
-->