<!-- 
***So sánh giữa MySQLi và PDO
- Hỗ trợ cơ sở dữ liệu:
MySQLi: Chỉ hỗ trợ MySQL.
PDO: Hỗ trợ nhiều loại cơ sở dữ liệu khác nhau(12 hệ quản trị csdl khác nhau)

-API:
MySQLi: Hỗ trợ cả giao diện hướng đối tượng và thủ tục.
PDO: Chỉ hỗ trợ giao diện hướng đối tượng.

-Prepared statements:
MySQLi: Có hỗ trợ.
PDO: Có hỗ trợ và rất mạnh mẽ.

-Đa chức năng:
MySQLi: Chỉ làm việc với MySQL, có thể không linh hoạt khi cần chuyển đổi cơ sở dữ liệu.
PDO: Linh hoạt hơn, dễ dàng chuyển đổi giữa các loại cơ sở dữ liệu khác nhau. 
=>ta thường sd mysqlLi hơn,nó cũng tương tự mysql PDO (giống sql server)
-->