<!-- phần chức năng bình luận khá dài và khó nên ta có 1 thư mục riêng để chứa và ta có 1 CSDL binhluan riêng để thực hành 
*** trong CSDL BÌNH LUẬN TA CẦN 3 BẢNG:
 -thành viên :chứa thông tin các thanh viên: mã, tên,user pass,
 -sản phẩm :mã sp, tên, giá, bảo hành
 -bình luận : mã bình luận, ND, người bình luận, mã sp bình luận
 
 => ta cần biết là ai(tài khoản) bình luận, bình luận ở sản phẩm nào, sau khi ng dùng bình luận thì các comment này sẽ đc lưu vào cái database lưu các bình luận này
 
-->